// AUTO-GENERATED by EasyDesign — do not edit by hand.
import * as React from 'react';

export default function Card(): React.ReactElement {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', background: 'var(--color-surface)', padding: 'var(--space-lg)', borderRadius: 'var(--radius-lg)', gap: 'var(--space-md)' }}>
      <img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='560' height='180'%3E%3Crect width='560' height='180' fill='%234f46e5'/%3E%3Ctext x='280' y='104' font-family='Helvetica,Arial,sans-serif' font-size='30' fill='white' text-anchor='middle'%3EEasyDesign%3C/text%3E%3C/svg%3E" alt="Welcome to EasyDesign" style={{ display: 'block', width: '100%', maxWidth: '560px', height: 'auto', borderRadius: 'var(--radius-lg)' }} />
      <h2 style={{ margin: '0', fontFamily: 'var(--font-family)', fontSize: 'var(--font-size-2xl)', lineHeight: 'var(--font-line-height-tight)', color: 'var(--color-text)', fontWeight: 'var(--font-weight-bold)' }}>Welcome aboard</h2>
      <p style={{ margin: '0', fontFamily: 'var(--font-family)', fontSize: 'var(--font-size-base)', lineHeight: 'var(--font-line-height-normal)', color: 'var(--color-text)', fontWeight: 'var(--font-weight-regular)' }}>Your account is ready. Start building your first design in minutes.</p>
      <div style={{ display: 'flex', flexDirection: 'row', gap: 'var(--space-md)' }}>
        <a href="#" style={{ display: 'inline-block', textAlign: 'center', textDecoration: 'none', padding: 'var(--space-sm) var(--space-md)', borderRadius: 'var(--radius-lg)', fontFamily: 'var(--font-family)', fontSize: 'var(--font-size-base)', fontWeight: 'var(--font-weight-semibold)', background: 'var(--color-brand)', color: 'var(--color-on-brand)' }}>Get started</a>
        <a href="#" style={{ display: 'inline-block', textAlign: 'center', textDecoration: 'none', padding: 'var(--space-sm) var(--space-md)', borderRadius: 'var(--radius-lg)', fontFamily: 'var(--font-family)', fontSize: 'var(--font-size-base)', fontWeight: 'var(--font-weight-semibold)', background: 'transparent', color: 'var(--color-brand)', border: '1px solid var(--color-brand)' }}>Learn more</a>
      </div>
    </div>
  );
}
