// React generator. Walks the IR (src/ir/walk) and emits .tsx component SOURCE
// (a string): a default-exported function component, inline style objects
// (camelCase keys), token-bound values as "var(--…)", className-free markup.
// α (structure + layout properties) comes from the walk; β (leaf CSS vocabulary)
// from leaf-style; only the JSX-source syntax + indentation live here. C = depth.
import { type Frame } from '../ir/types';
import { type Emitter, walkNode } from '../ir/walk';

import {
  buttonDecls,
  containerDecls,
  type Decl,
  imageDecls,
  structuralDecls,
  textDecls,
} from './leaf-style';

const INDENT = '  ';
function pad(depth: number): string {
  return INDENT.repeat(depth);
}
function reindent(src: string, levels: number): string {
  const prefix = INDENT.repeat(levels);
  return src
    .split('\n')
    .map((line) => (line.length ? prefix + line : line))
    .join('\n');
}
function escapeSingle(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
// Our decls are camelCase identifiers with string values, so this renders a
// React inline-style object literal: { display: 'flex', flexDirection: 'column' }.
function styleLiteral(decls: Decl[]): string {
  const entries = decls.map((d) => `${d.prop}: '${escapeSingle(d.value)}'`);
  return `{ ${entries.join(', ')} }`;
}
function jsxText(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\{/g, '&#123;')
    .replace(/\}/g, '&#125;');
}
function jsxAttr(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

const reactEmitter: Emitter<string, number> = {
  container(node, shape, children, depth) {
    const p = pad(depth);
    const decls = [...structuralDecls(shape), ...containerDecls(node.style)];
    if (shape.kind === 'flow' && shape.wrapChildren) {
      const cp = pad(depth + 1);
      // Each direct child sits side-by-side with flex:1 (rendered one level deeper).
      const inner = children
        .map((c) => `${cp}<div style={{ flex: 1 }}>\n${reindent(c, 1)}\n${cp}</div>`)
        .join('\n');
      return `${p}<div style={${styleLiteral(decls)}}>\n${inner}\n${p}</div>`;
    }
    return `${p}<div style={${styleLiteral(decls)}}>\n${children.join('\n')}\n${p}</div>`;
  },
  text(node, depth) {
    const tag = node.props.variant === 'h2' ? 'h2' : 'p';
    return `${pad(depth)}<${tag} style={${styleLiteral(textDecls(node))}}>${jsxText(node.props.content)}</${tag}>`;
  },
  button(node, depth) {
    return `${pad(depth)}<a href="#" style={${styleLiteral(buttonDecls(node))}}>${jsxText(node.props.content)}</a>`;
  },
  image(node, depth) {
    const { src, alt } = node.props;
    return `${pad(depth)}<img src="${jsxAttr(src)}" alt="${jsxAttr(alt)}" style={${styleLiteral(imageDecls(node))}} />`;
  },
  descend(depth) {
    return depth + 1;
  },
};

/** Emit the full .tsx component source for a Frame. */
export function emitReactSource(frame: Frame): string {
  const body = walkNode<string, number>(frame.root, 2, reactEmitter);
  return (
    `// AUTO-GENERATED by EasyDesign — do not edit by hand.\n` +
    `import * as React from 'react';\n\n` +
    `export default function Card(): React.ReactElement {\n` +
    `  return (\n${body}\n  );\n}\n`
  );
}
